const projects = [
  {
    id: 'proj_001',
    title: ' E-Commerce App',
    description: 'Complete shopping platform with cart, payments, admin dashboard, and order tracking.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://nikprojects-1.github.io/eCommerce/',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=340&fit=crop&auto=format',
    features: ['User Auth', 'Product Management', 'Cart & Checkout', 'Admin Panel', 'Order History'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/eCommerce/archive/refs/heads/main.zip'
  },
  {
    id: 'proj_002',
    title: 'Real-Time Chat Application',
    description: 'WhatsApp-style chat app with rooms, private messaging, and online status.',
    tech: ['React', 'Socket.io', 'Node.js', 'MongoDB'],
    price: 399,
    originalPrice: 599,
    discount: 33,
    demoUrl: 'https://your-demo-link.com/chat',
    thumbnail: 'https://images.unsplash.com/photo-1611746879615-1a8c5b5c6e0b?w=600&h=340&fit=crop&auto=format',
    features: ['Real-time Messaging', 'Chat Rooms', 'Private DMs', 'Online Status', 'File Sharing'],
    available: true,
  },
  {
    id: 'proj_003',
    title: 'Developer Portfolio Website',
    description: 'Clean, responsive portfolio with animations, project showcase, and contact form.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 299,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/portfolio',
    thumbnail: 'https://images.unsplash.com/photo-1542744175293-7a39f8e83fd?w=600&h=340&fit=crop&auto=format',
    features: ['Responsive Design', 'Smooth Animations', 'Project Gallery', 'Contact Form', 'Dark Mode'],
    available: true,
  },
  {
    id: 'proj_004',
    title: 'Task Management App',
    description: 'Trello-like kanban board with drag & drop, deadlines, and team collaboration.',
    tech: ['Vue.js', 'Firebase', 'Tailwind CSS'],
    price: 299,
    originalPrice: 699,
    discount: 57,
    demoUrl: 'https://nikprojects-1.github.io/TaskManager/',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=340&fit=crop&auto=format',
    features: ['Kanban Board', 'Drag & Drop', 'Team Sharing', 'Deadlines', 'Notifications'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/TaskManager/archive/refs/heads/main.zip'
  },
  {
    id: 'proj_005',
    title: 'Blog CMS Platform',
    description: 'Full-featured blog with markdown editor, categories, comments, and SEO.',
    tech: ['Next.js', 'PostgreSQL', 'Prisma'],
    price: 499,
    originalPrice: 799,
    discount: 38,
    demoUrl: 'https://your-demo-link.com/blog',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=340&fit=crop&auto=format',
    features: ['Markdown Editor', 'Categories & Tags', 'Comments', 'SEO Optimized', 'RSS Feed'],
  },
  {
    id: 'proj_006',
    title: 'Expense Tracker App',
    description: 'Track income and expenses with charts, budgets, and monthly reports.',
    tech: ['React', 'Chart.js', 'LocalStorage'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/expense',
    thumbnail: 'https://images.unsplash.com/photo-1554224154-260325c5f3be?w=600&h=340&fit=crop&auto=format',
    features: ['Income & Expense Tracking', 'Charts & Graphs', 'Budget Limits', 'Monthly Reports', 'Export CSV'],
  },
  {
    id: 'proj_007',
    title: 'Weather Dashboard',
    description: 'Real-time weather data with forecasts, maps, and alerts.',
    tech: ['JavaScript', 'Weather API', 'Chart.js'],
    price: 1,
    originalPrice: 249,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/weather',
    thumbnail: 'https://images.unsplash.com/photo-1592210455858-1e5a7c0b5c1d?w=600&h=340&fit=crop&auto=format',
    features: ['Current Weather', '7-Day Forecast', 'Location Search', 'Interactive Maps', 'Weather Alerts'],
  },
  {
    id: 'proj_008',
    title: 'Social Media Dashboard',
    description: 'Analytics dashboard for social media with scheduling and engagement metrics.',
    tech: ['React', 'Node.js', 'MongoDB', 'Chart.js'],
    price: 399,
    originalPrice: 999,
    discount: 60,
    demoUrl: 'https://your-demo-link.com/social',
    thumbnail: 'https://images.unsplash.com/photo-1460925855917-afdab827c52f?w=600&h=340&fit=crop&auto=format',
    features: ['Analytics Charts', 'Post Scheduling', 'Engagement Metrics', 'User Management', 'Export Reports'],
  },
  {
    id: 'proj_009',
    title: 'To-Do List App',
    description: 'Modern task manager with categories, priorities, and progress tracking.',
    tech: ['Vanilla JS', 'LocalStorage', 'CSS3'],
    price: 1,
    originalPrice: 199,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/todo',
    thumbnail: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=600&h=340&fit=crop&auto=format',
    features: ['Task Management', 'Categories', 'Priority Levels', 'Progress Tracking', 'Local Storage'],
  },
  {
    id: 'proj_010',
    title: 'Calculator App',
    description: 'Scientific calculator with history, themes, and keyboard support.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 149,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/calculator',
    thumbnail: 'https://images.unsplash.com/photo-1586953208448-b95a79798ec0?w=600&h=340&fit=crop&auto=format',
    features: ['Basic Operations', 'Scientific Functions', 'Calculation History', 'Dark Mode', 'Keyboard Support'],
  },
  {
    id: 'proj_011',
    title: 'Stopwatch App',
    description: 'Professional stopwatch with lap times, sessions, and sound alerts.',
    tech: ['JavaScript', 'CSS Animations', 'LocalStorage'],
    price: 1,
    originalPrice: 179,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/stopwatch',
    thumbnail: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b25?w=600&h=340&fit=crop&auto=format',
    features: ['Stopwatch', 'Countdown Timer', 'Lap Times', 'Session History', 'Sound Alerts'],
  },
  {
    id: 'proj_012',
    title: 'Notes App',
    description: 'Rich text notes with categories, search, and export features.',
    tech: ['React', 'LocalStorage', 'Rich Text Editor'],
    price: 1,
    originalPrice: 299,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/notes',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Rich Text Editor', 'Categories', 'Search', 'Local Storage', 'Export Notes'],
  },
  {
    id: 'proj_013',
    title: 'Quiz App',
    description: 'Interactive quiz app with scoring, timer, and multiple categories.',
    tech: ['React', 'Firebase', 'CSS3'],
    price: 1,
    originalPrice: 349,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/quiz',
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4177?w=600&h=340&fit=crop&auto=format',
    features: ['Multiple Categories', 'Score Tracking', 'Leaderboard', 'Timer', 'Progress Bar'],
  },
  {
    id: 'proj_014',
    title: 'Recipe Manager',
    description: 'Recipe app with search, categories, favorites, and ratings.',
    tech: ['Vue.js', 'API Integration', 'LocalStorage'],
    price: 1,
    originalPrice: 279,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/recipes',
    thumbnail: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=340&fit=crop&auto=format',
    features: ['Recipe Search', 'Category Filters', 'Favorites', 'Rating System', 'Ingredient List'],
  },
  {
    id: 'proj_015',
    title: 'Music Player',
    description: 'Modern music player with playlists, visualizer, and controls.',
    tech: ['JavaScript', 'Web Audio API', 'CSS3'],
    price: 1,
    originalPrice: 399,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/music',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa527?w=600&h=340&fit=crop&auto=format',
    features: ['Playback Controls', 'Playlist Management', 'Visualizer', 'Volume Control', 'Progress Bar'],
  },
  {
    id: 'proj_016',
    title: 'Password Generator',
    description: 'Secure password generator with customization and history.',
    tech: ['JavaScript', 'Crypto API', 'CSS3'],
    price: 1,
    originalPrice: 199,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/password',
    thumbnail: 'https://images.unsplash.com/photo-1560848302269-2a6b7c4a4b2?w=600&h=340&fit=crop&auto=format',
    features: ['Customizable Length', 'Character Options', 'Strength Indicator', 'Copy to Clipboard', 'History'],
  },
  {
    id: 'proj_017',
    title: 'Color Picker Tool',
    description: 'Advanced color picker with palettes, gradients, and export.',
    tech: ['HTML5', 'Canvas API', 'JavaScript'],
    price: 1,
    originalPrice: 249,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/colorpicker',
    thumbnail: 'https://images.unsplash.com/photo-1541701494577-c81a6328c71c?w=600&h=340&fit=crop&auto=format',
    features: ['Color Selection', 'Palette Generator', 'Gradient Creator', 'Export Formats', 'Color History'],
  },
  {
    id: 'proj_018',
    title: 'Unit Converter',
    description: 'Multi-unit converter with history and favorites.',
    tech: ['JavaScript', 'CSS3', 'LocalStorage'],
    price: 1,
    originalPrice: 189,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/converter',
    thumbnail: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&h=340&fit=crop&auto=format',
    features: ['Multiple Categories', 'Instant Conversion', 'Favorites', 'History', 'Decimal Precision'],
  },
  {
    id: 'proj_019',
    title: 'BMI Calculator',
    description: 'Health calculator with tracking, tips, and progress charts.',
    tech: ['React', 'Chart.js', 'Health APIs'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/bmi',
    thumbnail: 'https://images.unsplash.com/photo-1571017342657-5432a1816e67?w=600&h=340&fit=crop&auto=format',
    features: ['BMI Calculation', 'Health Tips', 'Progress Tracking', 'Charts', 'Goal Setting'],
  },
  {
    id: 'proj_020',
    title: 'Quote Generator',
    description: 'Daily quotes with categories, favorites, and sharing.',
    tech: ['JavaScript', 'Quote API', 'CSS3'],
    price: 199,
    originalPrice: 349,
    discount: 43,
    demoUrl: 'https://your-demo-link.com/quotes',
    thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e2f387?w=600&h=340&fit=crop&auto=format',
    features: ['Daily Quotes', 'Categories', 'Favorites', 'Social Sharing', 'Custom Backgrounds'],
  },
  {
    id: 'proj_021',
    title: 'World Clock',
    description: 'Multi-timezone clock with alarms and themes.',
    tech: ['JavaScript', 'Time APIs', 'CSS3'],
    price: 199,
    originalPrice: 299,
    discount: 33,
    demoUrl: 'https://your-demo-link.com/clock',
    thumbnail: 'https://images.unsplash.com/photo-1526506235274-aa7394baeb8a?w=600&h=340&fit=crop&auto=format',
    features: ['World Clock', 'Multiple Timezones', 'Alarms', 'Themes', 'Fullscreen Mode'],
  },
  {
    id: 'proj_022',
    title: 'URL Shortener',
    description: 'URL shortening service with analytics and custom links.',
    tech: ['Node.js', 'MongoDB', 'Express'],
    price: 199,
    originalPrice: 499,
    discount: 60,
    demoUrl: 'https://your-demo-link.com/shortener',
    thumbnail: 'https://images.unsplash.com/photo-1460925855917-afdab827c52f?w=600&h=340&fit=crop&auto=format',
    features: ['URL Shortening', 'Analytics', 'Custom Links', 'QR Codes', 'Link Management'],
  },
  {
    id: 'proj_023',
    title: 'Image Gallery',
    description: 'Responsive gallery with filters, lightbox, and upload.',
    tech: ['JavaScript', 'CSS Grid', 'Lazy Loading'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/gallery',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Image Upload', 'Filter & Search', 'Lightbox View', 'Responsive Grid', 'Lazy Loading'],
  },
  {
    id: 'proj_024',
    title: 'Survey Form',
    description: 'Dynamic survey builder with validation and analytics.',
    tech: ['React', 'Form Validation', 'Chart.js'],
    price: 199,
    originalPrice: 349,
    discount: 43,
    demoUrl: 'https://your-demo-link.com/survey',
    thumbnail: 'https://images.unsplash.com/photo-1554224154-260325c5f3be?w=600&h=340&fit=crop&auto=format',
    features: ['Form Builder', 'Question Types', 'Validation', 'Analytics', 'Export Results'],
  },
  {
    id: 'proj_025',
    title: 'File Manager',
    description: 'File management system with upload, organize, and preview.',
    tech: ['JavaScript', 'File API', 'CSS Grid'],
    price: 299,
    originalPrice: 599,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/filemanager',
    thumbnail: 'https://images.unsplash.com/photo-1554224154-260325c5f3be?w=600&h=340&fit=crop&auto=format',
    features: ['File Upload', 'Folder Organization', 'File Preview', 'Search & Filter', 'Drag & Drop'],
  },
  {
    id: 'proj_026',
    title: 'Calendar App',
    description: 'Interactive calendar with events, reminders, and sync.',
    tech: ['React', 'Date Picker', 'LocalStorage'],
    price: 299,
    originalPrice: 499,
    discount: 40,
    demoUrl: 'https://your-demo-link.com/calendar',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Event Management', 'Calendar View', 'Reminders', 'Recurring Events', 'Export Calendar'],
  },
  {
    id: 'proj_027',
    title: 'Chatbot Interface',
    description: 'AI-powered chatbot with NLP and responses.',
    tech: ['JavaScript', 'AI API', 'CSS3'],
    price: 399,
    originalPrice: 699,
    discount: 43,
    demoUrl: 'https://your-demo-link.com/chatbot',
    thumbnail: 'https://images.unsplash.com/photo-1538481199701-c410f6393c03?w=600&h=340&fit=crop&auto=format',
    features: ['AI Responses', 'Natural Language', 'Custom Training', 'Multi-language', 'Analytics'],
  },
  {
    id: 'proj_028',
    title: 'Video Player',
    description: 'Custom video player with controls, playlist, and subtitles.',
    tech: ['HTML5', 'JavaScript', 'CSS3'],
    price: 199,
    originalPrice: 349,
    discount: 43,
    demoUrl: 'https://your-demo-link.com/videoplayer',
    thumbnail: 'https://images.unsplash.com/photo-1522820799289-7fffa0c29812?w=600&h=340&fit=crop&auto=format',
    features: ['Video Controls', 'Playlist Support', 'Subtitle Support', 'Fullscreen Mode', 'Playback Speed'],
  },
  {
    id: 'proj_029',
    title: 'E-Learning Platform',
    description: 'Online learning platform with courses, quizzes, and progress.',
    tech: ['React', 'Node.js', 'MongoDB'],
    price: 599,
    originalPrice: 999,
    discount: 40,
    demoUrl: 'https://your-demo-link.com/elearning',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Course Management', 'Video Lessons', 'Quiz System', 'Progress Tracking', 'Certificates'],
  },
  {
    id: 'proj_030',
    title: 'Job Portal',
    description: 'Job board with applications, profiles, and notifications.',
    tech: ['React', 'Node.js', 'PostgreSQL'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://your-demo-link.com/jobs',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Job Listings', 'Application Tracking', 'Company Profiles', 'Resume Upload', 'Email Alerts'],
  },
  {
    id: 'proj_031',
    title: 'Fitness Tracker',
    description: 'Health and fitness tracker with workouts, goals, and progress.',
    tech: ['React', 'Health APIs', 'Chart.js'],
    price: 299,
    originalPrice: 599,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/fitness',
    thumbnail: 'https://images.unsplash.com/photo-1571017342657-5432a1816e67?w=600&h=340&fit=crop&auto=format',
    features: ['Workout Tracking', 'Goal Setting', 'Progress Charts', 'Health Metrics', 'Social Sharing'],
  },
  {
    id: 'proj_032',
    title: 'Booking System',
    description: 'Appointment booking system with calendar and notifications.',
    tech: ['Vue.js', 'Firebase', 'Tailwind CSS'],
    price: 399,
    originalPrice: 699,
    discount: 43,
    demoUrl: 'https://your-demo-link.com/booking',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Calendar Integration', 'Time Slots', 'Notifications', 'Payment Integration', 'Booking Management'],
  },
  {
    id: 'proj_033',
    title: 'Inventory Management',
    description: 'Stock management system with tracking, alerts, and reports.',
    tech: ['React', 'Node.js', 'MongoDB', 'Chart.js'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://your-demo-link.com/inventory',
    thumbnail: 'https://images.unsplash.com/photo-1554224154-260325c5f3be?w=600&h=340&fit=crop&auto=format',
    features: ['Stock Tracking', 'Low Stock Alerts', 'Reports & Analytics', 'Barcode Scanner', 'Multi-location'],
  }
];
