const projects = [
  {
    id: 'proj_001',
    title: ' E-Commerce App',
    description: 'Complete shopping platform with cart, payments, admin dashboard, and order tracking.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://nikprojects-1.github.io/eCommerce/',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=340&fit=crop&auto=format',
    features: ['User Auth', 'Product Management', 'Cart & Checkout', 'Admin Panel', 'Order History'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/eCommerce/archive/refs/heads/main.zip'
  },
  {
    id: 'proj_002',
    title: 'Real-Time Chat Application',
    description: 'WhatsApp-style chat app with rooms, private messaging, and online status.',
    tech: ['React', 'Socket.io', 'Node.js', 'MongoDB'],
    price: 399,
    originalPrice: 599,
    discount: 33,
    demoUrl: 'https://your-demo-link.com/chat',
    thumbnail: 'https://images.unsplash.com/photo-1611746879615-1a8c5b5c6e0b?w=600&h=340&fit=crop&auto=format',
    features: ['Real-time Messaging', 'Chat Rooms', 'Private DMs', 'Online Status', 'File Sharing'],
    available: true,
  },
  {
    id: 'proj_003',
    title: 'Developer Portfolio Website',
    description: 'Clean, responsive portfolio with animations, project showcase, and contact form.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 299,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/portfolio',
    thumbnail: 'https://images.unsplash.com/photo-1542744175293-7a39f8e83fd?w=600&h=340&fit=crop&auto=format',
    features: ['Responsive Design', 'Smooth Animations', 'Project Gallery', 'Contact Form', 'Dark Mode'],
    available: true,
  },
  {
    id: 'proj_004',
    title: 'Task Management App',
    description: 'Trello-like kanban board with drag & drop, deadlines, and team collaboration.',
    tech: ['Vue.js', 'Firebase', 'Tailwind CSS'],
    price: 299,
    originalPrice: 699,
    discount: 57,
    demoUrl: 'https://nikprojects-1.github.io/TaskManager/',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=340&fit=crop&auto=format',
    features: ['Kanban Board', 'Drag & Drop', 'Team Sharing', 'Deadlines', 'Notifications'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/TaskManager/archive/refs/heads/main.zip'
  },
  {
    id: 'proj_005',
    title: 'Blog CMS Platform',
    description: 'Full-featured blog with markdown editor, categories, comments, and SEO.',
    tech: ['Next.js', 'PostgreSQL', 'Prisma'],
    price: 499,
    originalPrice: 799,
    discount: 38,
    demoUrl: 'https://your-demo-link.com/blog',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=340&fit=crop&auto=format',
    features: ['Markdown Editor', 'Categories & Tags', 'Comments', 'SEO Optimized', 'RSS Feed'],
  },
  {
    id: 'proj_006',
    title: 'Expense Tracker App',
    description: 'Personal finance tracker with charts, budgets, and monthly reports.',
    tech: ['React', 'Chart.js', 'LocalStorage'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/expense',
    thumbnail: 'https://images.unsplash.com/photo-1554224154-260325c5f3be?w=600&h=340&fit=crop&auto=format',
    features: ['Income & Expense Tracking', 'Charts & Graphs', 'Budget Limits', 'Monthly Reports', 'Export CSV'],
  },
  {
    id: 'proj_007',
    title: 'Weather Dashboard',
    description: 'Beautiful weather app with forecasts, maps, and location search.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Weather API'],
    price: 1,
    originalPrice: 249,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/weather',
    thumbnail: 'https://images.unsplash.com/photo-1592210455858-1e5a7c0b5c1d?w=600&h=340&fit=crop&auto=format',
    features: ['Current Weather', '7-Day Forecast', 'Location Search', 'Interactive Maps', 'Weather Alerts'],
  },
  {
    id: 'proj_008',
    title: 'Social Media Dashboard',
    description: 'Analytics dashboard for social media with charts and insights.',
    tech: ['React', 'Chart.js', 'Node.js', 'Express'],
    price: 399,
    originalPrice: 999,
    discount: 60,
    demoUrl: 'https://your-demo-link.com/social',
    thumbnail: 'https://images.unsplash.com/photo-1460925855917-afdab827c52f?w=600&h=340&fit=crop&auto=format',
    features: ['Analytics Charts', 'Post Scheduling', 'Engagement Metrics', 'User Management', 'Export Reports'],
  },
  {
    id: 'proj_009',
    title: 'Todo List Application',
    description: 'Simple yet powerful todo app with categories, priorities, and progress tracking.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 199,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/todo',
    thumbnail: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=600&h=340&fit=crop&auto=format',
    features: ['Task Management', 'Categories', 'Priority Levels', 'Progress Tracking', 'Local Storage'],
  },
  {
    id: 'proj_010',
    title: 'Calculator App',
    description: 'Advanced calculator with scientific functions, history, and dark mode.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 149,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/calculator',
    thumbnail: 'https://images.unsplash.com/photo-1586953208448-b95a79798ec0?w=600&h=340&fit=crop&auto=format',
    features: ['Basic Operations', 'Scientific Functions', 'Calculation History', 'Dark Mode', 'Keyboard Support'],
  },
  {
    id: 'proj_011',
    title: 'Stopwatch Timer',
    description: 'Professional stopwatch with lap times, countdown timer, and session tracking.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 179,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/stopwatch',
    thumbnail: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b25?w=600&h=340&fit=crop&auto=format',
    features: ['Stopwatch', 'Countdown Timer', 'Lap Times', 'Session History', 'Sound Alerts'],
  },
  {
    id: 'proj_012',
    title: 'Notes App',
    description: 'Beautiful notes application with rich text, categories, and cloud sync.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 299,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/notes',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Rich Text Editor', 'Categories', 'Search', 'Local Storage', 'Export Notes'],
  },
  {
    id: 'proj_013',
    title: 'Quiz Application',
    description: 'Interactive quiz app with multiple categories, scoring, and leaderboards.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 349,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/quiz',
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4177?w=600&h=340&fit=crop&auto=format',
    features: ['Multiple Categories', 'Score Tracking', 'Leaderboard', 'Timer', 'Progress Bar'],
  },
  {
    id: 'proj_014',
    title: 'Recipe Finder',
    description: 'Recipe discovery app with search, filters, and favorite recipes collection.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 279,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/recipes',
    thumbnail: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=340&fit=crop&auto=format',
    features: ['Recipe Search', 'Category Filters', 'Favorites', 'Rating System', 'Ingredient List'],
  },
  {
    id: 'proj_015',
    title: 'Music Player',
    description: 'Elegant music player with playlist, controls, and visualizer effects.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 399,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/music',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa527?w=600&h=340&fit=crop&auto=format',
    features: ['Playback Controls', 'Playlist Management', 'Visualizer', 'Volume Control', 'Progress Bar'],
  },
  {
    id: 'proj_016',
    title: 'Password Generator',
    description: 'Secure password generator with customization options and strength indicator.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 199,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/password',
    thumbnail: 'https://images.unsplash.com/photo-1560848302269-2a6b7c4a4b2?w=600&h=340&fit=crop&auto=format',
    features: ['Customizable Length', 'Character Options', 'Strength Indicator', 'Copy to Clipboard', 'History'],
  },
  {
    id: 'proj_017',
    title: 'Color Picker Tool',
    description: 'Advanced color picker with palettes, gradients, and export options.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 249,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/colorpicker',
    thumbnail: 'https://images.unsplash.com/photo-1541701494577-c81a6328c71c?w=600&h=340&fit=crop&auto=format',
    features: ['Color Selection', 'Palette Generator', 'Gradient Creator', 'Export Formats', 'Color History'],
  },
  {
    id: 'proj_018',
    title: 'Unit Converter',
    description: 'Comprehensive unit converter for length, weight, temperature, and more.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 1,
    originalPrice: 189,
    discount: 99,
    demoUrl: 'https://your-demo-link.com/converter',
    thumbnail: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&h=340&fit=crop&auto=format',
    features: ['Multiple Categories', 'Instant Conversion', 'Favorites', 'History', 'Decimal Precision'],
  },
  {
    id: 'proj_019',
    title: 'BMI Calculator',
    description: 'Health and fitness BMI calculator with charts and health recommendations.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/bmi',
    thumbnail: 'https://images.unsplash.com/photo-1571017342657-5432a1816e67?w=600&h=340&fit=crop&auto=format',
    features: ['BMI Calculation', 'Health Tips', 'Progress Tracking', 'Charts', 'Goal Setting'],
  },
  {
    id: 'proj_020',
    title: 'Random Quote Generator',
    description: 'Inspirational quote generator with categories, favorites, and sharing options.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 349,
    discount: 43,
    demoUrl: 'https://your-demo-link.com/quotes',
    thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e2f387?w=600&h=340&fit=crop&auto=format',
    features: ['Daily Quotes', 'Categories', 'Favorites', 'Social Sharing', 'Custom Backgrounds'],
  },
  {
    id: 'proj_021',
    title: 'Digital Clock',
    description: 'Modern digital clock with world time, alarms, and beautiful themes.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 299,
    discount: 33,
    demoUrl: 'https://your-demo-link.com/clock',
    thumbnail: 'https://images.unsplash.com/photo-1526506235274-aa7394baeb8a?w=600&h=340&fit=crop&auto=format',
    features: ['World Clock', 'Multiple Timezones', 'Alarms', 'Themes', 'Fullscreen Mode'],
  },
  {
    id: 'proj_022',
    title: 'Link Shortener',
    description: 'URL shortener service with analytics, custom links, and QR codes.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 499,
    discount: 60,
    demoUrl: 'https://your-demo-link.com/shortener',
    thumbnail: 'https://images.unsplash.com/photo-1460925855917-afdab827c52f?w=600&h=340&fit=crop&auto=format',
    features: ['URL Shortening', 'Click Analytics', 'Custom Links', 'QR Generation', 'Link History'],
  },
  {
    id: 'proj_023',
    title: 'Image Gallery',
    description: 'Beautiful image gallery with filters, lightbox, and batch operations.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/gallery',
    thumbnail: 'https://images.unsplash.com/photo-1541963463532-681b5f5d4a2b?w=600&h=340&fit=crop&auto=format',
    features: ['Image Upload', 'Filters', 'Lightbox View', 'Batch Operations', 'Album Organization'],
  },
  {
    id: 'proj_024',
    title: 'Survey Form Builder',
    description: 'Dynamic survey form builder with multiple question types and results.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 599,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/survey',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=340&fit=crop&auto=format',
    features: ['Form Builder', 'Multiple Question Types', 'Results Dashboard', 'Data Export', 'Custom Themes'],
  },
  {
    id: 'proj_025',
    title: 'File Manager',
    description: 'Web-based file manager with upload, download, and organization features.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 699,
    discount: 57,
    demoUrl: 'https://your-demo-link.com/filemanager',
    thumbnail: 'https://images.unsplash.com/photo-1553729459-0850d6d96f7?w=600&h=340&fit=crop&auto=format',
    features: ['File Upload/Download', 'Folder Organization', 'Search', 'Preview', 'Batch Operations'],
  },
  {
    id: 'proj_026',
    title: 'Calendar App',
    description: 'Full-featured calendar with events, reminders, and scheduling.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 549,
    discount: 46,
    demoUrl: 'https://your-demo-link.com/calendar',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21e2e3020485?w=600&h=340&fit=crop&auto=format',
    features: ['Event Management', 'Reminders', 'Monthly View', 'Recurring Events', 'Export Calendar'],
  },
  {
    id: 'proj_027',
    title: 'Chatbot Interface',
    description: 'AI-powered chatbot interface with conversation history and responses.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 799,
    discount: 63,
    demoUrl: 'https://your-demo-link.com/chatbot',
    thumbnail: 'https://images.unsplash.com/photo-1531293065408-ea7e35f0f472?w=600&h=340&fit=crop&auto=format',
    features: ['Chat Interface', 'Conversation History', 'Quick Responses', 'Typing Indicators', 'Export Chats'],
  },
  {
    id: 'proj_028',
    title: 'Video Player',
    description: 'Custom video player with playlists, subtitles, and playback controls.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 499,
    discount: 40,
    demoUrl: 'https://your-demo-link.com/videoplayer',
    thumbnail: 'https://images.unsplash.com/photo-1522869667898-2e1adda9b76d?w=600&h=340&fit=crop&auto=format',
    features: ['Video Playback', 'Playlist Management', 'Subtitle Support', 'Playback Speed', 'Fullscreen Mode'],
  },
  {
    id: 'proj_029',
    title: 'E-Learning Platform',
    description: 'Educational platform with courses, quizzes, and progress tracking.',
    tech: ['React', 'Node.js', 'MongoDB'],
    price: 399,
    originalPrice: 899,
    discount: 56,
    demoUrl: 'https://your-demo-link.com/elearning',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e404f3?w=600&h=340&fit=crop&auto=format',
    features: ['Course Management', 'Video Lessons', 'Quiz System', 'Progress Tracking', 'Certificates'],
  },
  {
    id: 'proj_030',
    title: 'Job Portal',
    description: 'Complete job portal with listings, applications, and employer dashboard.',
    tech: ['React', 'Node.js', 'Express'],
    price: 399,
    originalPrice: 999,
    discount: 60,
    demoUrl: 'https://your-demo-link.com/jobs',
    thumbnail: 'https://images.unsplash.com/photo-1505755976225-9b49aeb9bde?w=600&h=340&fit=crop&auto=format',
    features: ['Job Listings', 'Application Tracking', 'Employer Dashboard', 'Resume Upload', 'Search Filters'],
  },
  {
    id: 'proj_031',
    title: 'Fitness Tracker',
    description: 'Comprehensive fitness tracking app with workouts, nutrition, and goals.',
    tech: ['React', 'Chart.js', 'LocalStorage'],
    price: 399,
    originalPrice: 799,
    discount: 50,
    demoUrl: 'https://your-demo-link.com/fitness',
    thumbnail: 'https://images.unsplash.com/photo-1571019613452-0742f9e8c2a?w=600&h=340&fit=crop&auto=format',
    features: ['Workout Logging', 'Nutrition Tracking', 'Goal Setting', 'Progress Charts', 'Exercise Library'],
  },
  {
    id: 'proj_032',
    title: 'Booking System',
    description: 'Multi-service booking system with calendar integration and notifications.',
    tech: ['Vue.js', 'Node.js', 'MongoDB'],
    price: 399,
    originalPrice: 899,
    discount: 56,
    demoUrl: 'https://your-demo-link.com/booking',
    thumbnail: 'https://images.unsplash.com/photo-1559526351-2b8be4e634db?w=600&h=340&fit=crop&auto=format',
    features: ['Service Booking', 'Calendar Integration', 'Automated Reminders', 'Payment Processing', 'Admin Dashboard'],
  },
  {
    id: 'proj_033',
    title: 'Inventory Management',
    description: 'Business inventory system with stock tracking, reports, and alerts.',
    tech: ['React', 'Node.js', 'Express'],
    price: 399,
    originalPrice: 999,
    discount: 60,
    demoUrl: 'https://your-demo-link.com/inventory',
    thumbnail: 'https://images.unsplash.com/photo-1586953208448-b95a79798ec0?w=600&h=340&fit=crop&auto=format',
    features: ['Stock Tracking', 'Low Stock Alerts', 'Sales Reports', 'Supplier Management', 'Barcode Scanner'],
  },
];
