const projects = [

  // ── ₹1 ── (5 projects)
  {
    id: 'proj_003',
    title: 'Developer Portfolio Website',
    description: 'Clean, responsive portfolio with animations, project showcase, and contact form.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 99,
    originalPrice: 499,
    discount: 80,
    demoUrl: 'https://Harshadip1.github.io/developer-portfolio/',
    thumbnail: 'https://images.reallygooddesigns.com/2025/02/developer_portfolio_website_examples.webp',
    features: ['Responsive Design', 'Smooth Animations', 'Project Gallery', 'Contact Form', 'Dark Mode'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/developer-portfolio/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_007',
    title: 'Weather Dashboard',
    description: 'Real-time weather data with forecasts, maps, and alerts.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 99,
    originalPrice: 399,
    discount: 75,
    demoUrl: 'https://Harshadip1.github.io/Weather-Dashboard/',
    thumbnail: 'https://thf.bing.com/th/id/OIP.CeDItgdthItF34K8J5LL3QHaFE?w=251&h=180&c=7&r=0&o=7&cb=thfc1falcon&dpr=1.3&pid=1.7&rm=3',
    features: ['Current Weather', '7-Day Forecast', 'Location Search', 'Interactive Maps', 'Weather Alerts'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Weather-Dashboard/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_009',
    title: 'To-Do List App',
    description: 'Modern task manager with categories, priorities, and progress tracking.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 99,
    originalPrice: 349,
    discount: 72,
    demoUrl: 'https://Harshadip1.github.io/To-Do-List/',
    thumbnail: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=600&h=340&fit=crop&auto=format',
    features: ['Task Management', 'Categories', 'Priority Levels', 'Progress Tracking', 'Local Storage'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/To-Do-List/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_010',
    title: 'Calculator App',
    description: 'Scientific calculator with history, themes, and keyboard support.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 99,
    originalPrice: 299,
    discount: 67,
    demoUrl: 'https://Harshadip1.github.io/Calculator-App/',
    thumbnail: 'https://sm.ign.com/ign_pk/news/a/apples-off/apples-official-calculator-app-finally-arrives-on-ipads_m19z.jpg',
    features: ['Basic Operations', 'Scientific Functions', 'Calculation History', 'Dark Mode', 'Keyboard Support'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Calculator-App/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_011',
    title: 'Stopwatch App',
    description: 'Professional stopwatch with lap times, sessions, and sound alerts.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 99,
    originalPrice: 329,
    discount: 70,
    demoUrl: 'https://Harshadip1.github.io/Stopwatch-App/',
    thumbnail: 'https://www.sourcecodester.com/sites/default/files/images/rems/sa1_0.png',
    features: ['Stopwatch', 'Countdown Timer', 'Lap Times', 'Session History', 'Sound Alerts'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Stopwatch-App/archive/refs/heads/main.zip',
  },

  // ── ₹199 ── (5 projects)
  {
    id: 'proj_006',
    title: 'Expense Tracker App',
    description: 'Track income and expenses with charts, budgets, and monthly reports.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://Harshadip1.github.io/Expense-Tracker/',
    thumbnail: 'https://cdn.dribbble.com/userupload/11281604/file/original-b7d3386b5723884976a5fe945bc11dd7.png?crop=255x0-2305x1538&resize=1600x1200',
    features: ['Income & Expense Tracking', 'Charts & Graphs', 'Budget Limits', 'Monthly Reports', 'Export CSV'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/Expense-Tracker/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_019',
    title: 'BMI Calculator',
    description: 'Health calculator with tracking, tips, and progress charts.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://Harshadip1.github.io/BMI-Calculator/',
    thumbnail: 'https://tse2.mm.bing.net/th/id/OIP.Zx_go-gFsPNBMA--GhzI2AHaFI?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['BMI Calculation', 'Health Tips', 'Progress Tracking', 'Charts', 'Goal Setting'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/BMI-Calculator/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_020',
    title: 'Quote Generator',
    description: 'Daily quotes with categories, favorites, and sharing.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 349,
    discount: 43,
    demoUrl: 'https://Harshadip1.github.io/Quote-Generator/',
    thumbnail: 'https://i.ytimg.com/vi/FiUVwPYYT5A/maxresdefault.jpg',
    features: ['Daily Quotes', 'Categories', 'Favorites', 'Social Sharing', 'Custom Backgrounds'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Quote-Generator/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_023',
    title: 'Image Gallery',
    description: 'Responsive gallery with filters, lightbox, and upload.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 399,
    discount: 50,
    demoUrl: 'https://Harshadip1.github.io/Image-Gallery/',
    thumbnail: 'https://www.photo.gallery/content/1.index/x3-photo-gallery-website.jpg',
    features: ['Image Upload', 'Filter & Search', 'Lightbox View', 'Responsive Grid', 'Lazy Loading'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Image-Gallery/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_024',
    title: 'Survey Form',
    description: 'Dynamic survey builder with validation and analytics.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 199,
    originalPrice: 349,
    discount: 43,
    demoUrl: 'https://Harshadip1.github.io/Survey-Form/',
    thumbnail: 'https://tse2.mm.bing.net/th/id/OIP.7-8ctNmf58VRldGjYkvsJgHaEK?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Form Builder', 'Question Types', 'Validation', 'Analytics', 'Export Results'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Survey-Form/archive/refs/heads/main.zip',
  },

  // ── ₹299 ── (5 projects)
  {
    id: 'proj_004',
    title: 'Task Management App',
    description: 'Trello-like kanban board with drag & drop, deadlines, and team collaboration.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 699,
    discount: 57,
    demoUrl: 'https://Harshadip1.github.io/task-manager/',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=340&fit=crop&auto=format',
    features: ['Kanban Board', 'Drag & Drop', 'Team Sharing', 'Deadlines', 'Notifications'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/task-manager/archive/refs/heads/master.zip'
  },
  {
    id: 'proj_025',
    title: 'File Manager',
    description: 'File management system with upload, organize, and preview.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 599,
    discount: 50,
    demoUrl: 'https://Harshadip1.github.io/File-Manager/',
    thumbnail: 'https://thf.bing.com/th/id/OIP.jJSn-u6Uo0O3NLXgw9bXbAHaFj?w=189&h=180&c=7&r=0&o=7&cb=thfc1falcon&dpr=1.3&pid=1.7&rm=3',
    features: ['File Upload', 'Folder Organization', 'File Preview', 'Search & Filter', 'Drag & Drop'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/File-Manager/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_026',
    title: 'Calendar App',
    description: 'Interactive calendar with events, reminders, and sync.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 499,
    discount: 40,
    demoUrl: 'https://Harshadip1.github.io/Calendar-App/',
    thumbnail: 'https://tse4.mm.bing.net/th/id/OIP.zOl7XmPZZOq4Yz2vjY0s5gHaFj?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Event Management', 'Calendar View', 'Reminders', 'Recurring Events', 'Export Calendar'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Calendar-App/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_031',
    title: 'Fitness Tracker',
    description: 'Health and fitness tracker with workouts, goals, and progress.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 599,
    discount: 50,
    demoUrl: 'https://Harshadip1.github.io/Fitness-Tracker/',
    thumbnail: 'https://tse1.mm.bing.net/th/id/OIP.BEDGb1M9JXOWoU3kgUF4OAHaEK?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Workout Tracking', 'Goal Setting', 'Progress Charts', 'Health Metrics', 'Social Sharing'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Fitness-Tracker/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_022',
    title: 'URL Shortener',
    description: 'URL shortening service with analytics and custom links.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 299,
    originalPrice: 499,
    discount: 40,
    demoUrl: 'https://Harshadip1.github.io/URL-Shortener/',
    thumbnail: 'https://tse2.mm.bing.net/th/id/OIP.2VwaAilKydv9_3r4caf7aQHaE7?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['URL Shortening', 'Analytics', 'Custom Links', 'QR Codes', 'Link Management'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/URL-Shortener/archive/refs/heads/main.zip',
  },

  // ── ₹399 ── (5 projects)
  {
    id: 'proj_002',
    title: 'Real-Time Chat Application',
    description: 'WhatsApp-style chat app with rooms, private messaging, and online status.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 399,
    originalPrice: 599,
    discount: 33,
    demoUrl: 'https://Harshadip1.github.io/Chat-Application/',
    thumbnail: 'https://thf.bing.com/th/id/OIP.5IDoQb86Ch_6BGgaMrE2HQHaEK?o=7&cb=thfc1falcon&rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Real-time Messaging', 'Chat Rooms', 'Private DMs', 'Online Status', 'File Sharing'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/Chat-Application/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_008',
    title: 'Social Media Dashboard',
    description: 'Analytics dashboard for social media with scheduling and engagement metrics.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 399,
    originalPrice: 999,
    discount: 60,
    demoUrl: 'https://Harshadip1.github.io/Social-Media/',
    thumbnail: 'https://tse3.mm.bing.net/th/id/OIP.ro5YgBPi7ysO-Wq_snXi8gHaE6?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Analytics Charts', 'Post Scheduling', 'Engagement Metrics', 'User Management', 'Export Reports'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/Social-Media/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_027',
    title: 'Chatbot Interface',
    description: 'AI-powered chatbot with NLP and responses.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 399,
    originalPrice: 699,
    discount: 43,
    demoUrl: 'https://Harshadip1.github.io/Chatbot-Interface/',
    thumbnail: 'https://mir-s3-cdn-cf.behance.net/project_modules/fs/8adc1e199119271.664c8b1c7b5a2.jpg',
    features: ['AI Responses', 'Natural Language', 'Custom Training', 'Multi-language', 'Analytics'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Chatbot-Interface/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_032',
    title: 'Booking System',
    description: 'Appointment booking system with calendar and notifications.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 399,
    originalPrice: 699,
    discount: 43,
    demoUrl: 'https://Harshadip1.github.io/Booking-System/',
    thumbnail: 'https://tse2.mm.bing.net/th/id/OIP.6ANP1MAL6HUVg0MecpPFvwHaE7?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Calendar Integration', 'Time Slots', 'Notifications', 'Payment Integration', 'Booking Management'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Booking-System/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_028',
    title: 'Video Player',
    description: 'Custom video player with controls, playlist, and subtitles.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 399,
    originalPrice: 699,
    discount: 43,
    demoUrl: 'https://Harshadip1.github.io/Video-Player/',
    thumbnail: 'https://tse2.mm.bing.net/th/id/OIP.4Lfyfrv_vFjEjHbt4IEaaAHaD4?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Video Controls', 'Playlist Support', 'Subtitle Support', 'Fullscreen Mode', 'Playback Speed'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Video-Player/archive/refs/heads/main.zip',
  },

  // ── ₹999 ── (premium projects)
  {
    id: 'proj_hms_001',
    title: '🏥 MediCore HMS (Hospital Management System)',
    description: 'Hospital Management System with React Native, Web Dashboard & Role-Based Access.',
    tech: ['React Native', 'Expo SDK', 'HTML', 'CSS', 'JavaScript', 'AsyncStorage', 'LocalStorage'],
    price: 999,
    originalPrice: 1499,
    discount: 33,
    demoUrl: 'https://harshadip1.github.io/hospital-management-system',
    thumbnail: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600&h=340&fit=crop&auto=format',
    features: [
      'React Native Mobile App',
      'Web Dashboard Included',
      '25+ Functional Screens',
      'Role-Based Login System',
      'Admin, Doctor, Nurse & Staff Panels',
      'Patient Management Module',
      'Doctor Management Module',
      'Appointment Booking System',
      'OPD Queue Management',
      'IPD/Admission & Discharge Management',
      'Laboratory Management',
      'Radiology Management',
      'Pharmacy Management',
      'Billing & Invoice System',
      'Inventory & Stock Management',
      'Emergency Patient Management',
      'Staff Management',
      'Reports & Analytics Dashboard',
      'Notifications & Messaging',
      'Search & Filter Functionality',
      'Responsive Design',
      'Offline Data Storage',
      'Clean Folder Structure',
      'Easy to Customize',
      'Ready for Viva & Project Submission',
      'Complete Source Code',
      'Project Documentation Included',
      'Installation Guide Included',
    ],
    available: true,
    githubZip: '',
    popular: true,
    downloads: [
      { label: '💻 Web Dashboard Code', icon: '🌐', url: 'https://github.com/Harshadip1/hospital-management-system/archive/refs/heads/main.zip', hint: 'HTML/CSS/JS source code for the web dashboard' },
      { label: '📱 React Native App Code', icon: '📱', url: 'https://github.com/Harshadip1/hospital-management-app/archive/refs/heads/main.zip', hint: 'Full React Native + Expo mobile app source code' },
      { label: '📦 APK File', icon: '📦', url: 'https://expo.dev/artifacts/eas/-OpHi_muwFhM9WEVFnpvRr2fC7v47HxbSGXBQAueEdI.apk', hint: 'Ready-to-install Android APK' },
      { label: '📄 Documentation', icon: '📄', url: 'https://raw.githubusercontent.com/Harshadip1/hospital-management-system/main/MediCore_HMS_Documentation.pdf', hint: 'Project report, setup guide & viva preparation' },
    ],
  },

  // ── ₹499 ── (5 projects)
  {
    id: 'proj_001',
    title: 'E-Commerce App',
    description: 'Complete shopping platform with cart, payments, admin dashboard, and order tracking.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://Harshadip1.github.io/eCommerce/',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=340&fit=crop&auto=format',
    features: ['User Auth', 'Product Management', 'Cart & Checkout', 'Admin Panel', 'Order History'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/eCommerce/archive/refs/heads/main.zip'
  },
  {
    id: 'proj_005',
    title: 'Blog CMS Platform',
    description: 'Full-featured blog with markdown editor, categories, comments, and SEO.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 799,
    discount: 38,
    demoUrl: 'https://Harshadip1.github.io/Blog-CMS-Platform/',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=340&fit=crop&auto=format',
    features: ['Markdown Editor', 'Categories & Tags', 'Comments', 'SEO Optimized', 'RSS Feed'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Blog-CMS-Platform/archive/refs/heads/main.zip'
  },
  {
    id: 'proj_030',
    title: 'Job Portal',
    description: 'Job board with applications, profiles, and notifications.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://Harshadip1.github.io/Job-Portal/',
    thumbnail: 'https://tse2.mm.bing.net/th/id/OIP.rHELcP3lV86n6gZ_vxXhsQHaE0?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Job Listings', 'Application Tracking', 'Company Profiles', 'Resume Upload', 'Email Alerts'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/Job-Portal/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_033',
    title: 'Inventory Management',
    description: 'Stock management system with tracking, alerts, and reports.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 899,
    discount: 44,
    demoUrl: 'https://Harshadip1.github.io/Inventory-Management/',
    thumbnail: 'https://tse4.mm.bing.net/th/id/OIP.G3pmn1yWmHUiVGdcRi-WSAHaFj?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Stock Tracking', 'Low Stock Alerts', 'Reports & Analytics', 'Barcode Scanner', 'Multi-location'],
    available: true,
    githubZip: 'https://github.com/Nikprojects-1/Inventory-Management/archive/refs/heads/main.zip',
  },
  {
    id: 'proj_029',
    title: 'E-Learning Platform',
    description: 'Online learning platform with courses, quizzes, and progress.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 499,
    originalPrice: 999,
    discount: 50,
    demoUrl: 'https://Harshadip1.github.io/E-Learning-Platform/',
    thumbnail: 'https://tse3.mm.bing.net/th/id/OIP.rm2XZVQLoLPJlnJ71BkCXAHaF5?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3',
    features: ['Course Management', 'Video Lessons', 'Quiz System', 'Progress Tracking', 'Certificates'],
    available: true,
    popular: true,
    githubZip: 'https://github.com/Nikprojects-1/E-Learning-Platform/archive/refs/heads/main.zip',
  },

];
